### ISSUE TITLE
Unknown database 'webcorpo_thai'

### ISSUE THREAD

**Issue by gree-gorey** [nevmenandr/thai-language#3]
говорит, нет такой базы(

весь текст ошибки:

```
Traceback (most recent call last):
  File "indexator.py", line 129, in <module>
    x = EANC_indexator(u'thai')
  File "indexator.py", line 32, in __init__
    self.mysql = corpusDB( self.config, language )      # Устанавливаем подключение к БД
  File "/var/www/web-corpora.net/ThaiCorpus/indexator/db.py", line 21, in __init__
    self.connect(language)
  File "/var/www/web-corpora.net/ThaiCorpus/indexator/db.py", line 31, in connect
    use_unicode = True
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1049, "Unknown database 'webcorpo_thai'")
```

файл **config.php** выглядит так:

```
[Database Params]
host = 127.0.0.1
database = webcorpo_thai
port = 3306
db_user = web****ra
db_pass = ******
encoding = utf8
```

причем судя по скрипту, он не пытается нигде ее создать, а как будто предполагается, что она уже должна существовать на момент запуска...

**Comment by nevmenandr** [comment]
Ой. Выкладывать пароль от базы в интернет -- не очень хорошая идея :(
В остальном -- понятно.

**Comment by gree-gorey** [comment]
уже заметил(

**Comment by nevmenandr** [comment]
Возможно, что база действительно должна быть создана заранее. Тогда нужно это сделать вручную, залогинившись на сервере и выполнив CREATE из консольного клиента mysql.

**Comment by gree-gorey** [comment]
спасибо, это помогло)

и у нас внимание... работает корпус!)))
